import { IMenus } from '../types';

const menus: IMenus = {
  id: 0,
  reskey: 'aab',
  resourcesType: 0,
  resourcesName: '用户管理后台',
  resourceUrl: '',
  own: 1,
  suns: [
    {
      id: 1,
      reskey: 'abc',
      resourcesType: 0,
      resourcesName: '控制台',
      resourceUrl: 'console',
      own: 0,
    },
    {
      id: 1,
      reskey: 'abc',
      resourcesType: 0,
      resourcesName: 'bbs管理',
      resourceUrl: 'console',
      own: 0,
    },
    {
      id: 1,
      reskey: 'abc',
      resourcesType: 0,
      resourcesName: 'blog管理',
      resourceUrl: 'console',
      own: 0,
    },
    {
      id: 1,
      reskey: 'abc',
      resourcesType: 0,
      resourcesName: '用户管理',
      resourceUrl: 'console',
      own: 0,
    },
    {
      id: 2,
      reskey: 'acd',
      resourcesType: 0,
      resourcesName: '用户反馈',
      resourceUrl: 'other',
      own: 0,
    },
    {
      id: 2,
      reskey: 'acd',
      resourcesType: 0,
      resourcesName: '信息管理',
      resourceUrl: 'other',
      own: 0,
    },
    {
      id: 2,
      reskey: 'acd',
      resourcesType: 0,
      resourcesName: '广告管理',
      resourceUrl: 'other',
      own: 0,
    },
    {
      id: 2,
      reskey: 'acd',
      resourcesType: 0,
      resourcesName: '系统设置',
      resourceUrl: 'other',
      own: 0,
    },
    {
      id: 2,
      reskey: 'acd',
      resourcesType: 0,
      resourcesName: '权限设置',
      resourceUrl: 'other',
      own: 0,
    },
    {
      id: 2,
      reskey: 'acd',
      resourcesType: 0,
      resourcesName: '其它',
      resourceUrl: 'other',
      own: 0,
    },
  ],
};

export default menus;
