import { IMenus } from '../types';

const menus: IMenus = {
  id: 0,
  reskey: 'e7isbi78il8bq5h56t843g',
  resourcesType: 0,
  resourcesName: '用户管理后台',
  resourceUrl: '',
  own: 1,
  suns: [
    {
      id: 1,
      reskey: 'e7isbi78il8bq5h56t843g',
      resourcesType: 0,
      resourcesName: '控制台',
      resourceUrl: 'console',
      own: 0,
    },
    {
      id: 1,
      reskey: 'shufi1ivmuou63dj6egpv8',
      resourcesType: 0,
      resourcesName: 'query管理',
      resourceUrl: 'console',
      own: 1,
      suns: [
        {
          id: 1,
          reskey: 'g4hdao6tkco3k7plplu1oo',
          resourcesType: 0,
          resourcesName: '问答管理',
          resourceUrl: 'console',
          own: 0,
        },
      ],
    },
    {
      id: 1,
      reskey: '62e5iotude8c78of9pql88',
      resourcesType: 0,
      resourcesName: 'bbs管理',
      resourceUrl: 'console',
      own: 0,
      suns: [
        {
          id: 1,
          reskey: 'acd',
          resourcesType: 0,
          resourcesName: '帖子管理',
          resourceUrl: 'console',
          own: 0,
        },
      ],
    },
    {
      id: 1,
      reskey: '3592ul476doe0rph9msdoo',
      resourcesType: 0,
      resourcesName: 'blog管理',
      resourceUrl: 'console',
      own: 0,
    },
    {
      id: 1,
      reskey: 's2t2uctr658fulibp45qmo',
      resourcesType: 0,
      resourcesName: '用户管理',
      resourceUrl: 'console',
      own: 0,
    },
    {
      id: 2,
      reskey: 'md81fj3ghk8joo41j6uvl8',
      resourcesType: 0,
      resourcesName: '用户反馈',
      resourceUrl: 'other',
      own: 0,
    },
    {
      id: 2,
      reskey: 'ev8shoj3abg7g236jm9ghg',
      resourcesType: 0,
      resourcesName: '信息管理',
      resourceUrl: 'other',
      own: 0,
    },
    {
      id: 2,
      reskey: 'etasf7puqbo_k193ej5jha',
      resourcesType: 0,
      resourcesName: '广告管理',
      resourceUrl: 'other',
      own: 0,
    },
    {
      id: 2,
      reskey: '8ptufrd89f8q8g3bl72q7g',
      resourcesType: 0,
      resourcesName: '系统设置',
      resourceUrl: 'other',
      own: 0,
    },
    {
      id: 2,
      reskey: 'oh23aqbjj3gg31uf4ikgho',
      resourcesType: 0,
      resourcesName: '权限设置',
      resourceUrl: 'other',
      own: 0,
    },
    {
      id: 2,
      reskey: '89fb9pdm5tggk356pkdm7o',
      resourcesType: 0,
      resourcesName: '其它',
      resourceUrl: 'other',
      own: 0,
    },
  ],
};

export default menus;
